"""Added share_count to Campaigns

Revision ID: 7b8d5c631f76
Revises: c0522c290f7c
Create Date: 2025-01-31 15:58:56.999035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8d5c631f76'
down_revision = 'c0522c290f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('share_count')

    # ### end Alembic commands ###
