"""Update Transaction Model - 7

Revision ID: c0522c290f7c
Revises: fdee94c949d8
Create Date: 2025-01-30 21:45:12.144740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0522c290f7c'
down_revision = 'fdee94c949d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_goal_amount', sa.Float(), server_default='0.0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('campaign_goal_amount')

    # ### end Alembic commands ###
